/* Tetiana Kodenko SQL
 PART1
to identify high-value customers it was decided to find out RFM values and score
as well as create segmentation for marketing purposes. This will help to provide
actionable insights that are valuable for strategic decisions in business.
*/
--collecting required data from tables with cte using aliases to create 'easy-to-read' query
WITH customers AS (
    SELECT
        DISTINCT(c_custkey) AS custkey,
        c_name AS customer,
        c_nationkey AS nationkey
    FROM
        SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER
),
countries AS (
    SELECT
        n_nationkey AS nationkey,
        n_name AS country
    FROM
        SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.NATION
),
orders_base AS (
    SELECT
        o_custkey AS custkey,
        o_orderkey AS orderkey,
        o_orderdate AS orderdate,
        -- lifetime from 1992-01-01 to 1998-08-02
        o_totalprice AS totalprice
    FROM
        SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.ORDERS
),
--RFM values, I decided to take as a current date 1998-08-03
RFM_values AS (
    SELECT
        custkey,
        MAX(orderdate) AS last_order_date,
        ROUND(AVG(totalprice), 2) AS avg_cust_revenue,
        DATEDIFF(days, last_order_date, '1998-08-03') AS R_value,
        COUNT(orderkey) AS F_value,
        SUM(totalprice) AS M_value
    FROM
        orders_base
    GROUP BY
        custkey
),
--RFM_values_median and quartiles to divide data into meaningful groups for scoring
RFM_values_medians AS (
    SELECT
        MIN(R_value) min_R,
        ROUND(MEDIAN(R_value), 0) med_R,
        MAX(R_value) max_R,
        ROUND((min_R + med_R) / 2, 1) AS Q1_R,
        ROUND((med_R + max_R) / 2, 1) AS Q3_R,
        MIN(F_value) min_F,
        ROUND(MEDIAN(F_value), 0) med_F,
        MAX(F_value) max_F,
        ROUND((min_F + med_F) / 2, 1) AS Q1_F,
        ROUND((med_F + max_F) / 2, 1) AS Q3_F,
        MIN(M_value) min_M,
        ROUND(MEDIAN(M_value), 0) med_M,
        MAX(M_value) max_M,
        ROUND((min_M + med_M) / 2, 1) AS Q1_M,
        ROUND((med_M + max_M) / 2, 1) AS Q3_M
    FROM
        RFM_values
),
--RFM scores based on RFM values and cross joined with rfm values medians.
RFM_scores AS (
    SELECT
        custkey,
        last_order_date,
        avg_cust_revenue,
        R_value,
        F_value,
        M_value,
        CASE
            WHEN R_value <= 30 THEN '1' --last month
            WHEN R_value <= 90 THEN '2' --last quarter
            WHEN R_value <= 365 THEN '3' --last year
            WHEN R_value > 365 THEN '4' --inactive/lost
        END AS R_score,
        CASE
            WHEN F_value <= Q1_F THEN '4' --from MIN to Q1 - lowest
            WHEN F_value <= med_F THEN '3' --from Q1 to Median
            WHEN F_value <= Q3_F THEN '2' -- from Median to Q3
            WHEN F_value > Q3_F THEN '1' --from Q3 to MAX - highest
        END AS F_score,
        CASE
            WHEN M_value <= Q1_M THEN '4' --from MIN to Q1 - lowest
            WHEN M_value <= med_M THEN '3' --from Q1 to Median
            WHEN M_value <= Q3_M THEN '2' -- from Median to Q3
            WHEN M_value > Q3_M THEN '1' --from Q3 to MAX - highest
        END AS M_score,
        R_score + F_score + M_score AS RFM_score,
        CASE
            WHEN RFM_score <= 4 THEN 'Champion'
            WHEN RFM_score <= 6 THEN 'Loyal'
            WHEN RFM_score <= 8 THEN 'Potential'
            WHEN RFM_score <= 10 THEN 'At Risk'
            WHEN RFM_score <= 12 THEN 'Churned'
        END AS segmentation
    FROM
        RFM_values
        CROSS JOIN RFM_values_medians
),
--final report combining RFM values,scores, customers and countries.
final_report AS (
    SELECT
        country,
        custkey,
        customer,
        last_order_date,
        avg_cust_revenue,
        R_value,
        --same as days since last purchase
        F_value,
        --same as total orders count per customer
        M_value,
        --same as total amount spent by customer
        R_score,
        F_score,
        M_score,
        RFM_score,
        segmentation
    FROM
        RFM_scores
        JOIN customers USING(custkey)
        JOIN countries USING(nationkey)
)
/*SELECT *
FROM final_report
ORDER BY  RFM_score, R_value, M_value DESC, F_value DESC;*/
/*--2 Calculate the total revenue generated by each segment 
----replace final select
SELECT 
segmentation,
SUM(M_value) AS total_spent
FROM final_report
GROUP BY segmentation
ORDER BY total_spent DESC;*/
/*--3 Identify the top 5 High Value customers by the RFM score.
----replace final select
SELECT 
RFM_score,
custkey,
customer,country

FROM final_report
ORDER BY RFM_score, R_value, M_value DESC, F_value DESC
--I used R_value as most important after RFM score because I feel like most recent purchases make a customer most 'alive', then M_value showing that customer spent a lot, and then F_value to sort out those who made most purchases. 
LIMIT 5;
*/
--4 Show which nations have the highest number of High Value customers.
----replace final select
SELECT
    country,
    COUNT(custkey) AS total_customers
FROM
    final_report
WHERE
    segmentation = 'Champion' --champions were chosen as High Value customers
GROUP BY
    country
ORDER BY
    total_customers DESC
LIMIT
    3;
--top 3 countries, remove to see whole list